// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /Users/jacfger/qmk_firmware/keyboards/splitkb/kyria/keymaps/jacfger/guraw.gif --output /Users/jacfger/qmk_firmware/keyboards/splitkb/kyria/keymaps/jacfger --format mono2 --no-rle True --no-deltas True`

#pragma once

#include <qp.h>

extern const uint32_t gfx_guraw_length;
extern const uint8_t  gfx_guraw[14724];
